# version: '3'

# services:
#   mlflow:
#     image: 'atcommons/mlflow-server'
#     build: .
#     ports:
#       - "5000:5000"
#     volumes:
#       - "./data:/mlflows"
#     environment:
#       BACKEND_URI: sqlite:////usr/src/mlflows//mlflow.db
#       ARTIFACT_ROOT: '/usr/src/mlruns'


# This version hides the underlying postgres database on a backend network
# different from the frontend network on which nginx interfaces mlflow.
# And mlflow is hidden behind nginx, allowing user auth to be implemented.
# 
# Have the following environment vars set in shell before running docker-compose
# (suggested values here but can use whatever desired):
# export mlflow=mlflowdb
# export mlflow=postgres
# export mlflow=<somepassword>
# export DB_PORT=5432
# export MLFLOW_PORT=5000
#
# AWS S3 bucket can be used instead of local drive for artifacts store via
# commented-out environment lines below.

version: '3.3'

services:
    db:
        restart: always
        image: postgres
        container_name: mlflow_db
        expose:
            - 8000
        networks:
            - backend
        environment:
            - MUID=$UID
            - MGID=$GID
            - POSTGRES_DB=mlflow
            - POSTGRES_USER=mlflow
            - POSTGRES_PASSWORD=mlflow
        volumes:
            - db_datapg:/var/lib/postgresql/data

    app:
        restart: always
        # build: ./notebooks
        image: mlflow_server
        container_name: mlflow_server
        expose:
            - 5001
        networks:
            - frontend
            - backend
        environment:
            - BACKEND=postgresql://mlflow:mlflow@db:5001/mlflow
            - ARTIFACTS=/mlruns
          # For artifact store in AWS S3 (note boto was installed in container):
          #  - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          #  - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          #  - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
          #  - ARTIFACTS="s3://mlflow_bucket/mlflow/"
        volumes:
            - mlrun_data:/mlruns
            - condenv:/opt/conda
        command: 
            - sh    # (sh allows for var substitution of BACKEND and ARTIFACTS)
            - -c
            - mlflow server 
                --port 5001  
                --host 0.0.0.0 
                --backend-store-uri $${BACKEND} 
                --default-artifact-root $${ARTIFACTS}
        depends_on:
            - db

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge

volumes:
    db_datapg:
    mlrun_data:
    condenv: